import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode, type CSSProperties } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { CartProvider } from "../context/CartContext";
import { siteConfig } from "@/config/siteConfig";
function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold text-foreground">404</h1><h2 className="mt-4 text-xl font-semibold text-foreground">Página não encontrada</h2><p className="mt-2 text-sm text-muted-foreground">O endereço que você procura não existe ou foi alterado.</p><Link to="/" className="mt-6 inline-flex rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Voltar ao início</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"});},[error]);return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold">Não foi possível carregar a página</h1><p className="mt-2 text-sm text-muted-foreground">Tente novamente ou volte ao início.</p><div className="mt-6 flex justify-center gap-2"><button onClick={()=>{router.invalidate();reset()}} className="rounded-md bg-primary px-4 py-2 text-sm text-white">Tentar novamente</button><a href="/" className="rounded-md border px-4 py-2 text-sm">Início</a></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:siteConfig.seo.title},{name:"description",content:siteConfig.seo.description},{name:"author",content:siteConfig.brand.name},{property:"og:title",content:siteConfig.seo.title},{property:"og:description",content:siteConfig.seo.description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"icon",href:siteConfig.brand.favicon},{rel:"canonical",href:siteConfig.seo.canonical}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="pt-BR"><head><HeadContent/></head><body style={{ "--primary": siteConfig.theme.primary, "--primary-foreground": "#ffffff", "--secondary": siteConfig.theme.secondary, "--secondary-foreground": siteConfig.theme.primary, "--accent": siteConfig.theme.secondary, "--accent-foreground": siteConfig.theme.primary, "--ring": siteConfig.theme.primary, "--border": "#e5e5e5", "--input": "#e5e5e5", "--muted": "#f1f1f1", "--muted-foreground": "#666666", "--background": "#fafafa", "--foreground": "#171717", "--card": "#ffffff", "--card-foreground": "#171717", "--popover": "#ffffff", "--popover-foreground": "#171717", "--chart-1": siteConfig.theme.primary, "--chart-2": siteConfig.theme.secondary } as CSSProperties}>{children}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:siteConfig.brand.name,url:siteConfig.seo.canonical,logo:`${siteConfig.seo.canonical}${siteConfig.brand.logo}`,sameAs:[siteConfig.social.instagram]})}}/><Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><CartProvider><Outlet/></CartProvider></QueryClientProvider>}
