/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LinksRouteImport } from './routes/links'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as GuiaIndexRouteImport } from './routes/guia.index'
import { Route as GuiaSlugRouteImport } from './routes/guia.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasRoute = PoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaIndexRoute = GuiaIndexRouteImport.update({
  id: '/guia/',
  path: '/guia/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaSlugRoute = GuiaSlugRouteImport.update({
  id: '/guia/$slug',
  path: '/guia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/links': typeof LinksRoute
  '/politicas': typeof PoliticasRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/guia/': typeof GuiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/links': typeof LinksRoute
  '/politicas': typeof PoliticasRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/guia': typeof GuiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/links': typeof LinksRoute
  '/politicas': typeof PoliticasRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/guia/': typeof GuiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/links'
    | '/politicas'
    | '/guia/$slug'
    | '/produto/$slug'
    | '/guia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/links'
    | '/politicas'
    | '/guia/$slug'
    | '/produto/$slug'
    | '/guia'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/links'
    | '/politicas'
    | '/guia/$slug'
    | '/produto/$slug'
    | '/guia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  LinksRoute: typeof LinksRoute
  PoliticasRoute: typeof PoliticasRoute
  GuiaSlugRoute: typeof GuiaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  GuiaIndexRoute: typeof GuiaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas': {
      id: '/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof PoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/': {
      id: '/guia/'
      path: '/guia'
      fullPath: '/guia/'
      preLoaderRoute: typeof GuiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/$slug': {
      id: '/guia/$slug'
      path: '/guia/$slug'
      fullPath: '/guia/$slug'
      preLoaderRoute: typeof GuiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  LinksRoute: LinksRoute,
  PoliticasRoute: PoliticasRoute,
  GuiaSlugRoute: GuiaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  GuiaIndexRoute: GuiaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
